<?php

namespace App\Http\Requests\Post;

use Illuminate\Foundation\Http\FormRequest;

class UpdatePostRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $id = $this->route('post');
        return [
            'title'             => "required|max:255|unique:posts,title,$id,id",
            'title_seo'         => 'max:191',
            'description_seo'   => 'max:191',
            'description'       => 'required',
            'content'           => 'required',
            'category'          => 'required|array',
            'post_tag'          => 'array',
            'photo'             => 'mimes:png,jpg,gif,svg|max:2048'
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
